### ISSUE TITLE
Development. [ QUESTION ] 

### ISSUE THREAD

**Issue by killerclaws12** [MatteoLeonesi/DiscordBot-AnimalCrossing-VillagerSimulator#2]
Hey! I love this idea of making a animal crossing Discord bot and I was wondering if I can collaborate with you? Like me being the 2nd developer and all of that? Ofc i will only take credits for my parts but it would help you out alot if you did have a 2nd developer. I also tried to add you on discord, my username and tag is: Sparky!!#9383

**Comment by MatteoLeonesi** [comment]
hi! sure! i'll add you this evening !
